(TeX-add-style-hook "hw1"
 (lambda ()
    (LaTeX-add-labels
     "uncommute"
     "commute"
     "uncommutemult"
     "commutemult"
     "addunassoc"
     "addassoc"
     "unassoc"
     "assoc")
    (TeX-add-symbols
     "tab"
     "gap")
    (TeX-run-style-hooks
     "fancyhdr"
     "geometry"
     "verbatim"
     "appendix"
     "microtype"
     "siunitx"
     "url"
     "multirow"
     "mathtools"
     "amsfonts"
     "amsmath"
     "graphicx"
     "enumerate"
     "babel"
     "english"
     "inputenc"
     "utf8"
     "setspace"
     "latex2e"
     "art12"
     "article"
     "letterpaper"
     "12pt")))

